kafka:
  topic:
    user-random-topic: user-random-topic
    user-created-topic: user-created-topic

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


      properties:
        spring:
          json:
            add:
              type:
                headers: false

    #    schema:
     #     registry:
      #      url: "http://127.0.0.1:8081"

